CREATE TABLE [dbo].[case_timestamp] (
    [cts_cas_key]                       INT           NOT NULL,
    [cts_waiting_to_accept_est]         DATETIME      NULL,
    [cts_waiting_to_accept_utc]         DATETIME      NULL,
    [cts_accepted_est]                  DATETIME      NULL,
    [cts_accepted_utc]                  DATETIME      NULL,
    [cts_waiting_to_accept_accept_sec]  BIGINT        NULL,
    [cts_arrival_to_needle_sec]         BIGINT        NULL,
    [cts_physician_mdm_sec]             BIGINT        NULL,
    [cts_response_sec]                  BIGINT        NULL,
    [cts_symptom_to_needle_sec]         BIGINT        NULL,
    [cts_last_known_well_to_needle_sec] BIGINT        NULL,
    [cts_bedside_response_sec]          BIGINT        NULL,
    [cts_start_to_stamp_sec]            BIGINT        NULL,
    [cts_start_to_accept_sec]           BIGINT        NULL,
    [cts_arrival_to_stamp_sec]          BIGINT        NULL,
    [cts_arrival_to_start_sec]          BIGINT        NULL,
    [cts_cpoe_order_to_needle]          BIGINT        NULL,
    [cts_login_to_handle_sec]           BIGINT        NULL,
    [cts_on_screen_sec]                 BIGINT        NULL,
    [cts_verbal_order_to_cpoe_sec]      BIGINT        NULL,
    [cts_verbal_order_to_needle_sec]    BIGINT        NULL,
    [cts_created_date]                  DATETIME      NULL,
    [cts_created_by]                    VARCHAR (128) NULL,
    [cts_modified_date]                 DATETIME      NULL,
    [cts_modified_by]                   VARCHAR (128) NULL,
    [cts_callback_to_tsnotification] BIGINT NULL, 
    CONSTRAINT [PK_case_timestamp] PRIMARY KEY CLUSTERED ([cts_cas_key] ASC)
);

