CREATE TABLE [dbo].[mock_case] (
    [mcas_key]                                             INT              IDENTITY (20000, 1) NOT NULL,
    [mcas_ctp_key]                                         INT              NOT NULL,
    [mcas_associate_id]                                    NVARCHAR (128)   NOT NULL,
    [mcas_fac_key]                                         UNIQUEIDENTIFIER NOT NULL,
    [mcas_callback]                                        VARCHAR (50)     NULL,
    [mcas_cart]                                            NVARCHAR (MAX)   NULL,
    [mcas_phy_key]                                         NVARCHAR (128)   NULL,
    [mcas_cst_key]                                         INT              NOT NULL,
    [mcas_notes]                                           VARCHAR (MAX)    NULL,
    [mcas_patient]                                         VARCHAR (300)    NULL,
    [mcas_case_number]                                     BIGINT           NULL,
    [mcas_response_date_consult]                           DATETIME         NULL,
    [mcas_response_reviewer]                               VARCHAR (300)    NULL,
    [mcas_response_phy_key]                                NVARCHAR (128)   NULL,
    [mcas_response_response_time]                          DATETIME         NULL,
    [mcas_response_ts_notification]                        DATETIME         NULL,
    [mcas_response_time_physician]                         DATETIME         NULL,
    [mcas_response_first_atempt]                           DATETIME         NULL,
    [mcas_response_case_research]                          NVARCHAR (MAX)   NULL,
    [mcas_response_technical_issues]                       INT              CONSTRAINT [DF_mcase_cas_response_technical_issues] DEFAULT ((2)) NOT NULL,
    [mcas_physician_concurrent_alerts]                     INT              CONSTRAINT [DF_mcase_cas_response_concurrent_alerts] DEFAULT ((2)) NOT NULL,
    [mcas_response_nav_to_ts]                              INT              CONSTRAINT [DF_mcase_cas_response_nav_to_ts] DEFAULT ((2)) NOT NULL,
    [mcas_response_miscommunication]                       INT              CONSTRAINT [DF_mcase_cas_response_miscommunication] DEFAULT ((2)) NOT NULL,
    [mcas_response_pulled_rounding]                        INT              CONSTRAINT [DF_mcase_cas_response_pulled_rounding] DEFAULT ((2)) NOT NULL,
    [mcas_response_inaccurate_eta]                         INT              CONSTRAINT [DF_mcase_cas_response_inaccurate_eta] DEFAULT ((2)) NOT NULL,
    [mcas_response_physician_blast]                        INT              CONSTRAINT [DF_mcase_cas_response_physician_blast] DEFAULT ((2)) NOT NULL,
    [mcas_response_rca_tracker]                            INT              CONSTRAINT [DF_mcase_cas_response_rca_tracker] DEFAULT ((2)) NOT NULL,
    [mcas_response_review_initiated]                       INT              CONSTRAINT [DF_mcase_cas_response_review_initiated] DEFAULT ((2)) NOT NULL,
    [mcas_response_case_number]                            VARCHAR (50)     NULL,
    [mcas_response_tpa_to_minute]                          INT              CONSTRAINT [DF__mcase__cas_respon__32816A03] DEFAULT ((3)) NOT NULL,
    [mcas_response_door_to_needle]                         INT              CONSTRAINT [DF__mcase__cas_respon__33758E3C] DEFAULT ((3)) NOT NULL,
    [mcas_patient_type]                                    INT              CONSTRAINT [DF__mcase__cas_patien__47477CBF] DEFAULT ((1)) NULL,
    [mcas_eta]                                             VARCHAR (250)    NULL,
    [mcas_status_assign_date]                              DATETIME         NULL,
    [mcas_ani]                                             VARCHAR (250)    NULL,
    [mcas_dnis]                                            VARCHAR (250)    NULL,
    [mcas_time_stamp]                                      DATETIME         NULL,
    [mcas_call_id]                                         VARCHAR (250)    NULL,
    [mcas_callback_extension]                              VARCHAR (50)     NULL,
    [mcas_caller]                                          VARCHAR (50)     NULL,
    [mcas_is_active]                                       BIT              CONSTRAINT [DF_mcase_cas_is_active_1] DEFAULT ((1)) NOT NULL,
    [mcas_created_by]                                      NVARCHAR (128)   NOT NULL,
    [mcas_created_by_name]                                 VARCHAR (300)    NULL,
    [mcas_created_date]                                    DATETIME         CONSTRAINT [DF_mcase_cas_created_date] DEFAULT (getdate()) NOT NULL,
    [mcas_modified_by]                                     NVARCHAR (128)   NULL,
    [mcas_modified_by_name]                                VARCHAR (300)    NULL,
    [mcas_modified_date]                                   DATETIME         NULL,
    [mcas_identification_type]                             INT              NULL,
    [mcas_identification_number]                           VARCHAR (50)     NULL,
    [mcas_pulled_from_rounding]                            BIT              CONSTRAINT [DF_mcase_case_pulled_from_rounding] DEFAULT ((0)) NOT NULL,
    [mcas_last_4_of_ssn]                                   VARCHAR (50)     NULL,
    [mcas_referring_physician]                             VARCHAR (500)    NULL,
    [mcas_follow_up_date]                                  DATE             NULL,
    [mcas_billing_dob]                                     DATETIME         NULL,
    [mcas_physician_assign_date]                           DATETIME         NULL,
    [mcas_followup_case_key]                               INT              NULL,
    [mcas_batch_id]                                        VARCHAR (128)    NULL,
    [mcas_is_flagged]                                      BIT              CONSTRAINT [DF_mcase_cas_is_flagged] DEFAULT ((0)) NOT NULL,
    [mcas_phy_technical_issue_date_est]                    DATETIME         NULL,
    [mcas_phy_technical_issue_date]                        DATETIME         NULL,
    [mcas_phy_has_technical_issue]                         BIT              CONSTRAINT [DF_mcase_cas_phy_has_technical_issue] DEFAULT ((0)) NOT NULL,
    [mcas_triage_notes]                                    VARCHAR (MAX)    NULL,
    [mcas_call_type]                                       INT              NULL,
    [mcas_callback_response_time_est]                      DATETIME         NULL,
    [mcas_callback_response_time]                          DATETIME         NULL,
    [mcas_caller_source_key]                               INT              NULL,
    [mcas_caller_source_text]                              NVARCHAR (MAX)   NULL,
    [mcas_is_partial_update]                               BIT              CONSTRAINT [DF_mcase_cas_is_partial_update] DEFAULT ((0)) NOT NULL,
    [mcas_is_flagged_dashboard]                            BIT              CONSTRAINT [DF_mcase_cas_is_flagged_dashboard] DEFAULT ((0)) NOT NULL,
    [mcas_cart_location_key]                               INT              NULL,
    [mcas_cart_location_text]                              NVARCHAR (MAX)   NULL,
    [mcas_work_flow_ids]                                   NVARCHAR (150)   NULL,
    [mcas_qps_assigned]                                    NVARCHAR (150)   NULL,
    [mcas_cancelled_type]                                  NVARCHAR (128)   NULL,
    [mcas_cancelled_text]                                  NVARCHAR (MAX)   NULL,
    [mcas_datetime_of_contact]                             NVARCHAR (250)   NULL,
    [mcas_typeof_correspondence]                           NVARCHAR (250)   NULL,
    [mcas_contact_comments]                                NVARCHAR (MAX)   NULL,
    [mcas_callback_response_by]                            NVARCHAR (250)   NULL,
    [mcas_callback_notes]                                  NVARCHAR (MAX)   NULL,
    [mcas_navigator_notes]                                 VARCHAR (MAX)    NULL,
    [mcas_rejection_type]                                  VARCHAR (128)    NULL,
    [mcas_rejection_text]                                  VARCHAR (MAX)    NULL,
    [mcas_is_flagged_physician]                            BIT              CONSTRAINT [Const_mcas_is_flagged_physician] DEFAULT ('false') NOT NULL,
    [mcas_nurse_identify_members_in_room]                  BIT              CONSTRAINT [DF__mock_case__mcas___38845C1C] DEFAULT ((0)) NULL,
    [mcas_nursing_verbalize_pre_CT_process]                BIT              CONSTRAINT [DF__mock_case__mcas___39788055] DEFAULT ((0)) NULL,
    [mcas_nursing_verbalize_post_CT_process]               BIT              CONSTRAINT [DF__mock_case__mcas___3A6CA48E] DEFAULT ((0)) NULL,
    [mcas_nursing_demonstrate_positioninig_cart]           BIT              CONSTRAINT [DF__mock_case__mcas___3B60C8C7] DEFAULT ((0)) NULL,
    [mcas_NIHSS_assessment_booklet_at_bedside]             BIT              CONSTRAINT [DF__mock_case__mcas___3C54ED00] DEFAULT ((0)) NULL,
    [mcas_nurse_assisst_completion_NIHSS_exam]             BIT              CONSTRAINT [DF__mock_case__mcas___3D491139] DEFAULT ((0)) NULL,
    [mcas_LOC_following_commands]                          BIT              CONSTRAINT [DF__mock_case__mcas___3E3D3572] DEFAULT ((0)) NULL,
    [mcas_visual_field_patient_looking_examiner_periphery] BIT              CONSTRAINT [DF__mock_case__mcas___3F3159AB] DEFAULT ((0)) NULL,
    [mcas_EOM_slow_motion]                                 BIT              CONSTRAINT [DF__mock_case__mcas___40257DE4] DEFAULT ((0)) NULL,
    [mcas_facial_symmetry]                                 BIT              NULL,
    [mcas_motor_drift_extensor_drift]                      BIT              CONSTRAINT [DF__mock_case__mcas___4119A21D] DEFAULT ((0)) NULL,
    [mcas_coordination_stretch_finger]                     BIT              CONSTRAINT [DF__mock_case__mcas___420DC656] DEFAULT ((0)) NULL,
    [mcas_sensory_broken_Q_tip]                            BIT              CONSTRAINT [DF__mock_case__mcas___4301EA8F] DEFAULT ((0)) NULL,
    [mcas_sensory_taps_bare_skin]                          BIT              CONSTRAINT [DF__mock_case__mcas___43F60EC8] DEFAULT ((0)) NULL,
    [mcas_neglect_unilaterly_then_bilaterally]             BIT              CONSTRAINT [DF__mock_case__mcas___44EA3301] DEFAULT ((0)) NULL,
    [mcas_neglect_primary_sensation_visual_neglect]        BIT              CONSTRAINT [DF__mock_case__mcas___45DE573A] DEFAULT ((0)) NULL,
    [mcas_neglect_visual_neglect_exam]                     BIT              CONSTRAINT [DF__mock_case__mcas___46D27B73] DEFAULT ((0)) NULL,
    [mcas_speech_exam_stroke_assessment_booklet]           BIT              CONSTRAINT [DF__mock_case__mcas___47C69FAC] DEFAULT ((0)) NULL,
    [mcas_language_exam_repetition_words]                  BIT              CONSTRAINT [DF__mock_case__mcas___48BAC3E5] DEFAULT ((0)) NULL,
    [mcas_nursing_verbalize_transfer_patient]              BIT              CONSTRAINT [DF__mock_case__mcas___49AEE81E] DEFAULT ((0)) NULL,
    [mcas_connectivity_issue]                              BIT              CONSTRAINT [DF__mock_case__mcas___4AA30C57] DEFAULT ((0)) NULL,
    [mcas_is_nav_blast]                                    BIT              NULL,
    [mcas_mock_drill_comments]                             VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_mock_case] PRIMARY KEY CLUSTERED ([mcas_key] ASC),
    CONSTRAINT [FK_mock_case_AspNetUsers] FOREIGN KEY ([mcas_response_phy_key]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_mock_case_AspNetUsers_Navigator] FOREIGN KEY ([mcas_associate_id]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_mock_case_AspNetUsers1] FOREIGN KEY ([mcas_phy_key]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_mock_case_facility] FOREIGN KEY ([mcas_fac_key]) REFERENCES [dbo].[facility] ([fac_key]) ON DELETE CASCADE ON UPDATE CASCADE
);

