CREATE TABLE [dbo].[case_template_telestroke_notpa] (
    [ctt_cas_key]                               INT            NOT NULL,
    [ctt_impression]                            VARCHAR (50)   NULL,
    [ctt_impression_text]                       VARCHAR (MAX)  NULL,
    [ctt_mechanism_stroke]                      VARCHAR (50)   NULL,
    [ctt_mechanism_stroke_text]                 VARCHAR (MAX)  NULL,
    [ctt_comment]                               VARCHAR (MAX)  NULL,
    [ctt_routine_consultation]                  BIT            CONSTRAINT [DF_case_template_telestroke_notpa_ctt_routine_consultation] DEFAULT ((0)) NOT NULL,
    [ctt_nihss_totalscore]                      INT            NULL,
    [ctt_sign_out]                              VARCHAR (50)   NULL,
    [ctt_created_date]                          DATETIME       NOT NULL,
    [ctt_created_by]                            VARCHAR (128)  NOT NULL,
    [ctt_created_by_name]                       VARCHAR (300)  NOT NULL,
    [ctt_modified_by]                           VARCHAR (128)  NULL,
    [ctt_modfied_by_name]                       VARCHAR (300)  NULL,
    [ctt_modified_date]                         DATETIME       NULL,
    [ctt_antiplatelet_therapy_recommedned]      VARCHAR (50)   NULL,
    [ctt_antiplatelet_therapy_recommedned_text] VARCHAR (MAX)  NULL,
    [ctt_vitals_bp]                             VARCHAR (MAX)  NULL,
    [ctt_vitals_pulse]                          VARCHAR (MAX)  NULL,
    [ctt_vitals_blood_glucose]                  VARCHAR (MAX)  NULL,
    [ctt_patient_family_cosulted]               BIT            NULL,
    [ctt_critical_care_was_provided]            BIT            NULL,
    [ctt_critical_care_minutes]                 INT            NULL,
    [ctt_imaging]                               VARCHAR (50)   NULL,
    [ctt_therapies]                             VARCHAR (50)   NULL,
    [ctt_other_workup]                          VARCHAR (50)   NULL,
    [ctt_neuro_exam]                            VARCHAR (50)   NULL,
    [ctt_speech]                                VARCHAR (50)   NULL,
    [ctt_language]                              VARCHAR (50)   NULL,
    [ctt_face]                                  VARCHAR (50)   NULL,
    [ctt_facial_sensation]                      VARCHAR (50)   NULL,
    [ctt_visual]                                VARCHAR (50)   NULL,
    [ctt_extraocular_movement]                  VARCHAR (50)   NULL,
    [ctt_motor]                                 VARCHAR (50)   NULL,
    [ctt_sensation]                             VARCHAR (50)   NULL,
    [ctt_coordination]                          VARCHAR (50)   NULL,
    [ctt_consented_to_tele]                     VARCHAR (50)   NULL,
    [ctt_disposition]                           VARCHAR (50)   NULL,
    [ctt_nihss_or_neuro]                        VARCHAR (50)   NULL,
    [ctt_cheif_complaints]                      NVARCHAR (MAX) NULL,
    [ctt_exam_free_text]                        NVARCHAR (MAX) NULL,
    [ctt_family_consent_available]              BIT            NULL,
    [ctt_PMH]                                   VARCHAR (50)   NULL,
    [ctt_anticoagulant_use]                     BIT            NULL,
    [ctt_anticoagulant_use_text]                VARCHAR (MAX)  NULL,
    [ctt_antiplatelet_use]                      BIT            NULL,
    [ctt_antiplatelet_use_text]                 VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_case_template_telestroke_notpa] PRIMARY KEY CLUSTERED ([ctt_cas_key] ASC),
    CONSTRAINT [FK_case_template_telestroke_notpa_case] FOREIGN KEY ([ctt_cas_key]) REFERENCES [dbo].[case] ([cas_key])
);

