CREATE TABLE [dbo].[cases_bak1] (
    [cas_key]                                                                              INT              IDENTITY (20000, 1) NOT NULL,
    [cas_ctp_key]                                                                          INT              NOT NULL,
    [cas_associate_id]                                                                     NVARCHAR (128)   NOT NULL,
    [cas_fac_key]                                                                          UNIQUEIDENTIFIER NOT NULL,
    [cas_callback]                                                                         VARCHAR (50)     NULL,
    [cas_cart]                                                                             NVARCHAR (50)    NULL,
    [cas_phy_key]                                                                          NVARCHAR (128)   NULL,
    [cas_cst_key]                                                                          INT              NOT NULL,
    [cas_notes]                                                                            VARCHAR (MAX)    NULL,
    [cas_patient]                                                                          VARCHAR (300)    NULL,
    [cas_case_number]                                                                      BIGINT           NULL,
    [cas_metric_lastwell_date]                                                             DATETIME         NULL,
    [cas_metric_door_time]                                                                 DATETIME         NULL,
    [cas_metric_stamp_time]                                                                DATETIME         NULL,
    [cas_metric_firstlogin_date]                                                           DATETIME         NULL,
    [cas_metric_assesment_time]                                                            DATETIME         NULL,
    [cas_metric_pa_ordertime]                                                              DATETIME         NULL,
    [cas_metric_needle_time]                                                               DATETIME         NULL,
    [cas_metric_consult_endtime]                                                           DATETIME         NULL,
    [cas_metric_lastwell_date_est]                                                         DATETIME         NULL,
    [cas_metric_door_time_est]                                                             DATETIME         NULL,
    [cas_metric_stamp_time_est]                                                            DATETIME         NULL,
    [cas_metric_firstlogin_date_est]                                                       DATETIME         NULL,
    [cas_metric_assesment_time_est]                                                        DATETIME         NULL,
    [cas_metric_pa_ordertime_est]                                                          DATETIME         NULL,
    [cas_metric_needle_time_est]                                                           DATETIME         NULL,
    [cas_metric_consult_endtime_est]                                                       DATETIME         NULL,
    [cas_metric_notes]                                                                     VARCHAR (MAX)    NULL,
    [cas_billing_date_of_consult]                                                          DATETIME         NULL,
    [cas_billing_patient_name]                                                             VARCHAR (300)    NULL,
    [cas_billing_mrn_fin]                                                                  NVARCHAR (20)    NULL,
    [cas_billing_dob]                                                                      DATETIME         NULL,
    [cas_billing_visit_type]                                                               VARCHAR (20)     NULL,
    [cas_billing_lod_key]                                                                  INT              NULL,
    [cas_billing_bic_key]                                                                  INT              NULL,
    [cas_billing_diagnosis]                                                                VARCHAR (MAX)    NULL,
    [cas_billing_notes]                                                                    VARCHAR (MAX)    NULL,
    [cas_billing_tpa_delay_notes]                                                          VARCHAR (MAX)    NULL,
    [cas_response_date_consult]                                                            DATETIME         NULL,
    [cas_response_reviewer]                                                                VARCHAR (300)    NULL,
    [cas_response_phy_key]                                                                 NVARCHAR (128)   NULL,
    [cas_response_response_time]                                                           DATETIME         NULL,
    [cas_response_ts_notification]                                                         DATETIME         NULL,
    [cas_response_zinc_notification]                                                       DATETIME         NULL,
    [cas_response_time_physician]                                                          DATETIME         NULL,
    [cas_response_first_atempt]                                                            DATETIME         NULL,
    [cas_response_sa_stat]                                                                 VARCHAR (20)     NULL,
    [cas_response_case_research]                                                           NVARCHAR (MAX)   NULL,
    [cas_response_sa_ts_md]                                                                INT              NOT NULL,
    [cas_response_technical_issues]                                                        INT              NOT NULL,
    [cas_physician_concurrent_alerts]                                                      INT              NOT NULL,
    [cas_response_nav_to_ts]                                                               INT              NOT NULL,
    [cas_response_miscommunication]                                                        INT              NOT NULL,
    [cas_response_pulled_rounding]                                                         INT              NOT NULL,
    [cas_response_inaccurate_eta]                                                          INT              NOT NULL,
    [cas_response_physician_blast]                                                         INT              NOT NULL,
    [cas_response_rca_tracker]                                                             INT              NOT NULL,
    [cas_response_review_initiated]                                                        INT              NOT NULL,
    [cas_response_case_number]                                                             VARCHAR (50)     NULL,
    [cas_billing_bic_key2]                                                                 INT              NULL,
    [cas_metric_video_end_time]                                                            DATETIME         NULL,
    [cas_metric_documentation_end_time]                                                    DATETIME         NULL,
    [cas_metric_video_end_time_est]                                                        DATETIME         NULL,
    [cas_metric_documentation_end_time_est]                                                DATETIME         NULL,
    [cas_metric_is_neuro_interventional]                                                   BIT              NULL,
    [cas_mrn_number]                                                                       VARCHAR (250)    NULL,
    [cas_navigator_concurrent_alerts]                                                      INT              NULL,
    [cas_response_tpa_to_minute]                                                           INT              NOT NULL,
    [cas_response_door_to_needle]                                                          INT              NOT NULL,
    [cas_patient_type]                                                                     INT              NULL,
    [cas_eta]                                                                              VARCHAR (250)    NULL,
    [cas_metric_tpa_consult]                                                               BIT              NOT NULL,
    [cas_status_assign_date]                                                               DATETIME         NULL,
    [cas_metric_video_start_time]                                                          DATETIME         NULL,
    [cas_metric_video_start_time_est]                                                      DATETIME         NULL,
    [cas_ani]                                                                              VARCHAR (250)    NULL,
    [cas_dnis]                                                                             VARCHAR (250)    NULL,
    [cas_time_stamp]                                                                       DATETIME         NULL,
    [cas_campaign_id]                                                                      VARCHAR (250)    NULL,
    [cas_call_id]                                                                          VARCHAR (250)    NULL,
    [cas_callback_extension]                                                               VARCHAR (50)     NULL,
    [cas_history_physician_initial_cal]                                                    VARCHAR (MAX)    NULL,
    [cas_caller]                                                                           VARCHAR (50)     NULL,
    [cas_is_active]                                                                        BIT              NOT NULL,
    [cas_created_by]                                                                       NVARCHAR (128)   NOT NULL,
    [cas_created_by_name]                                                                  VARCHAR (300)    NULL,
    [cas_created_date]                                                                     DATETIME         NOT NULL,
    [cas_modified_by]                                                                      NVARCHAR (128)   NULL,
    [cas_modified_by_name]                                                                 VARCHAR (300)    NULL,
    [cas_modified_date]                                                                    DATETIME         NULL,
    [cas_metric_symptoms]                                                                  NVARCHAR (MAX)   NULL,
    [cas_identification_type]                                                              INT              NULL,
    [cas_identification_number]                                                            VARCHAR (50)     NULL,
    [cas_metric_last_seen_normal]                                                          INT              NOT NULL,
    [cas_metric_has_hemorrhgic_history]                                                    INT              NOT NULL,
    [cas_metric_has_recent_anticoagulants]                                                 INT              NOT NULL,
    [cas_metric_has_major_surgery_history]                                                 INT              NOT NULL,
    [cas_metric_has_stroke_history]                                                        INT              NOT NULL,
    [cas_metric_tpa_verbal_order_time]                                                     DATETIME         NULL,
    [cas_metric_tpa_verbal_order_time_est]                                                 DATETIME         NULL,
    [cas_metric_weight]                                                                    FLOAT (53)       NULL,
    [cas_metric_weight_unit]                                                               VARCHAR (20)     NULL,
    [cas_metric_tpaDelay_key]                                                              INT              NULL,
    [cas_metric_non_tpa_reason_key]                                                        INT              NULL,
    [cas_metric_non_tpa_reason_text]                                                       NVARCHAR (MAX)   NULL,
    [cas_metric_ct_head_has_no_acture_hemorrhage]                                          BIT              NOT NULL,
    [cas_metric_ct_head_is_reviewed]                                                       BIT              NOT NULL,
    [cas_metric_advance_imaging_to_be_reviewed]                                            BIT              NOT NULL,
    [cas_metric_advance_imaging_is_reviewed]                                               BIT              NOT NULL,
    [cas_metric_advance_imaging_not_obtained]                                              BIT              NOT NULL,
    [cas_metric_advance_imaging_cta_head_checked_obtained]                                 BIT              NOT NULL,
    [cas_metric_advance_imaging_ctp_obtained]                                              BIT              NOT NULL,
    [cas_metric_discussed_with_neurointerventionalist]                                     BIT              NULL,
    [cas_metric_physician_notified_of_thrombolytics]                                       BIT              NULL,
    [cas_metric_physician_recommented_consult_neurointerventionalist]                      BIT              NOT NULL,
    [cas_billing_physician_blast]                                                          BIT              NOT NULL,
    [cas_is_nav_blast]                                                                     BIT              NOT NULL,
    [cas_pulled_from_rounding]                                                             BIT              NOT NULL,
    [cas_five9_original_stamp_time]                                                        VARCHAR (50)     NULL,
    [cas_last_4_of_ssn]                                                                    VARCHAR (50)     NULL,
    [cas_referring_physician]                                                              VARCHAR (500)    NULL,
    [cas_follow_up_date]                                                                   DATE             NULL,
    [cas_metric_ct_head_is_not_reviewed]                                                   BIT              NOT NULL,
    [cas_metric_is_lastwell_unknown]                                                       BIT              NOT NULL,
    [cas_metric_total_dose]                                                                DECIMAL (18, 10) NULL,
    [cas_metric_bolus]                                                                     DECIMAL (18, 10) NULL,
    [cas_metric_infusion]                                                                  DECIMAL (18, 10) NULL,
    [cas_metric_discard_quantity]                                                          DECIMAL (18, 10) NULL,
    [cas_billing_physician_blast_date]                                                     DATETIME         NULL,
    [cas_billing_physician_blast_date_est]                                                 DATETIME         NULL,
    [cas_physician_assign_date]                                                            DATETIME         NULL,
    [cas_is_ealert]                                                                        BIT              NOT NULL,
    [cas_metric_hpi]                                                                       NVARCHAR (MAX)   NULL,
    [cas_metric_patient_gender]                                                            VARCHAR (20)     NULL,
    [cas_metric_advance_imaging_no_indication_thombus]                                     BIT              NOT NULL,
    [cas_followup_case_key]                                                                INT              NULL,
    [cas_metric_radiologist_callback_for_review_of_advance_imaging]                        BIT              NULL,
    [cas_metric_radiologist_callback_for_review_of_advance_imaging_notes]                  NVARCHAR (MAX)   NULL,
    [cas_metric_radiologist_callback_for_review_of_advance_imaging_date]                   DATETIME         NULL,
    [cas_metric_discussed_with_neurointerventionalist_notes]                               NVARCHAR (MAX)   NULL,
    [cas_metric_discussed_with_neurointerventionalist_date]                                DATETIME         NULL,
    [cas_metric_physician_notified_of_thrombolytics_notes]                                 NVARCHAR (MAX)   NULL,
    [cas_metric_physician_notified_of_thrombolytics_date]                                  DATETIME         NULL,
    [cas_batch_id]                                                                         VARCHAR (128)    NULL,
    [cas_is_flagged]                                                                       BIT              NOT NULL,
    [cas_nihss_cannot_completed]                                                           BIT              NOT NULL,
    [cas_metric_ct_head_reviewed_text]                                                     VARCHAR (MAX)    NULL,
    [cas_phy_technical_issue_date_est]                                                     DATETIME         NULL,
    [cas_phy_technical_issue_date]                                                         DATETIME         NULL,
    [cas_phy_has_technical_issue]                                                          BIT              NOT NULL,
    [cas_triage_notes]                                                                     VARCHAR (MAX)    NULL,
    [cas_call_type]                                                                        INT              NULL,
    [cas_callback_response_time_est]                                                       DATETIME         NULL,
    [cas_callback_response_time]                                                           DATETIME         NULL,
    [cas_metric_symptom_onset_during_ed_stay]                                              BIT              NOT NULL,
    [cas_caller_source_key]                                                                INT              NULL,
    [cas_caller_source_text]                                                               NVARCHAR (MAX)   NULL,
    [cas_metric_presentation_suggestive]                                                   BIT              NOT NULL,
    [cas_metric_presentation_is_not_suggestive]                                            BIT              NOT NULL,
    [cas_metric_in_cta_queue]                                                              BIT              NOT NULL,
    [cas_is_partial_update]                                                                BIT              NOT NULL,
    [cas_is_flagged_dashboard]                                                             BIT              NOT NULL,
    [cas_cart_location_key]                                                                INT              NULL,
    [cas_cart_location_text]                                                               NVARCHAR (MAX)   NULL,
    [cas_metric_thrombectomy_medical_decision_making]                                      INT              NULL,
    [cas_metric_advance_imaging_cta_head_and_neck]                                         BIT              NOT NULL,
    [cas_metric_advance_imaging_ct_perfusion]                                              BIT              NOT NULL,
    [cas_metric_advance_imaging_to_be_reviewed_by_ed_provider_and_nir]                     BIT              NOT NULL,
    [cas_metric_advance_imaging_is_suggestive_of_large_vessel_occlusion]                   BIT              NOT NULL,
    [cas_metric_advance_imaging_reviewed_no_indication_of_large_vessel_occlusive_thrombus] BIT              NOT NULL,
    [cas_billing_comments]                                                                 VARCHAR (MAX)    NULL,
    [cas_work_flow_ids]                                                                    NVARCHAR (150)   NULL,
    [cas_qps_assigned]                                                                     INT              NULL,
    [cas_triage_arivalstarttodelay]                                                        NVARCHAR (250)   NULL,
    [cas_triage_recognition]                                                               NVARCHAR (250)   NULL,
    [cas_triage_strokealertrigger]                                                         NVARCHAR (250)   NULL,
    [cas_triage_transportandrooming]                                                       NVARCHAR (250)   NULL,
    [cas_ems_arivaltostarttimedelay]                                                       NVARCHAR (250)   NULL,
    [cas_ems_poor_identification]                                                          NVARCHAR (250)   NULL,
    [cas_inpatient_timefirstlogintonhssstartitme]                                          NVARCHAR (250)   NULL,
    [cas_inpatient_timefirstlogintovideostart]                                             NVARCHAR (250)   NULL,
    [cas_inpatient_arivaltoneedletime]                                                     NVARCHAR (250)   NULL,
    [cas_inpatient_related_imaging]                                                        NVARCHAR (250)   NULL,
    [cas_inpatient_unenhancedct]                                                           NVARCHAR (250)   NULL,
    [cas_inpatient_telemedicineassessmentroom]                                             NVARCHAR (250)   NULL,
    [cas_inpatient_telemedicineasesmentinct]                                               NVARCHAR (250)   NULL,
    [cas_inpatient_bpmanagemntrelated]                                                     NVARCHAR (250)   NULL,
    [cas_inpatient_workflowbeforemixing]                                                   NVARCHAR (250)   NULL,
    [cas_inpatient_workflowaftermixing]                                                    NVARCHAR (250)   NULL,
    [cas_ems_identification_occurred]                                                      NVARCHAR (250)   NULL,
    [cas_inpatient_delaysrelated_imaging]                                                  NVARCHAR (250)   NULL,
    [cas_inpatient_detection_hypertension]                                                 NVARCHAR (250)   NULL,
    [cas_inpatient_poormanagement_hypertension]                                            NVARCHAR (250)   NULL,
    [cas_inpatient_tpaadministration_delays]                                               NVARCHAR (250)   NULL,
    [cas_inpatient_system]                                                                 NVARCHAR (250)   NULL,
    [cas_inpatient_physician_related]                                                      NVARCHAR (250)   NULL,
    [cas_inpatient_centralizedpharmacy_delivery]                                           NVARCHAR (250)   NULL,
    [cas_inpatientdelays_mixing]                                                           NVARCHAR (250)   NULL,
    [cas_rca_primarydetail]                                                                NVARCHAR (250)   NULL,
    [cas_response_case_qps_assessment]                                                     NVARCHAR (MAX)   NULL,
    [cas_response_case_qps_reviewed]                                                       INT              NULL,
    [cas_response_case_facility_request_reviewed]                                          INT              NULL,
    [cas_history_physician_initial]                                                        VARCHAR (3000)   NULL,
    [cas_metric_symptom_onset_during_ed_stay_time_est]                                     DATETIME         NULL,
    [cas_metric_symptom_onset_during_ed_stay_time]                                         DATETIME         NULL,
    [TemplateEntityType]                                                                   INT              NULL,
    [cas_operations_review]                                                                NVARCHAR (MAX)   NULL
);

