CREATE TABLE [dbo].[facility_physician] (
    [fap_key]                                      INT              IDENTITY (1, 1) NOT NULL,
    [fap_fac_key]                                  UNIQUEIDENTIFIER NOT NULL,
    [fap_user_key]                                 NVARCHAR (128)   NOT NULL,
    [fap_is_active]                                BIT              CONSTRAINT [DF_facility_physician_fap_is_active] DEFAULT ((0)) NOT NULL,
    [fap_created_date]                             DATETIME         NOT NULL,
    [fap_created_by]                               NVARCHAR (128)   NOT NULL,
    [fap_modified_date]                            DATETIME         NULL,
    [fap_modified_by]                              NVARCHAR (128)   NULL,
    [fap_start_date]                               DATETIME         NULL,
    [fap_end_date]                                 DATETIME         NULL,
    [fap_is_on_boarded]                            BIT              CONSTRAINT [DF_facility_physician_fap_is_on_boarded] DEFAULT ((0)) NOT NULL,
    [fap_created_by_name]                          VARCHAR (300)    NULL,
    [fap_modified_by_name]                         VARCHAR (300)    NULL,
    [fap_is_override]                              BIT              CONSTRAINT [DF_facility_physician_fap_is_override] DEFAULT ((0)) NOT NULL,
    [fap_override_start]                           DATETIME         NULL,
    [fap_override_hours]                           INT              NULL,
    [fap_onboarding_complete_provider_active_date] DATETIME         NULL,
    [fap_is_hide_pending_onboarding]               BIT              CONSTRAINT [DF_facility_physician_fap_is_hide_pending_onboarding] DEFAULT ((0)) NOT NULL,
    [fap_onboarded_date]                           DATETIME         NULL,
    [fap_onboarded_by]                             NVARCHAR (128)   NULL,
    [fap_onboarded_by_name]                        VARCHAR (300)    NULL,
    [fap_hide]                                     BIT              CONSTRAINT [DF__facility___fap_h__15F0E3A4] DEFAULT ((0)) NOT NULL,
    [fap_credential_specialist]                    VARCHAR (300)    NULL,
    [fap_app_specialist]                           VARCHAR (300)    NULL,
    [fap_date_assigned]                            DATETIME         NULL,
    [fap_initial_app_received]                     DATETIME         NULL,
    [fap_app_started]                              DATETIME         NULL,
    [fap_app_submitted_to_hospital]                DATETIME         NULL,
    [fap_vcaa_date]                                DATETIME         NULL,
    [fap_anticipated_start]                        DATETIME         NULL,
    [fap_preapp_request_date]                      DATETIME         NULL,
    [fap_preapp_submitted_date]                    DATETIME         NULL,
    [fap_preapp_receive_date]                      DATETIME         NULL,
    [fap_app_sent_to_dr]                           DATETIME         NULL,
    [fap_Credentials_confirmed_date]               DATETIME         NULL,
    [fap_Password]                                 NVARCHAR (MAX)   NULL,
    [fap_Password_BY]                              NVARCHAR (100)   NULL,
    [fap_Password_Date]                            DATETIME         NULL,
    [fap_Array_path]                               NVARCHAR (MAX)   NULL,
    [fap_UserName]                                 NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_facility_physician] PRIMARY KEY CLUSTERED ([fap_key] ASC),
    CONSTRAINT [FK_facility_physician_AspNetUsers] FOREIGN KEY ([fap_user_key]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_facility_physician_facility] FOREIGN KEY ([fap_fac_key]) REFERENCES [dbo].[facility] ([fac_key]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [NIX_user_facility]
    ON [dbo].[facility_physician]([fap_user_key] ASC, [fap_fac_key] ASC, [fap_is_active] ASC);

