CREATE TABLE [dbo].[facility_questionnaire_pre_live] (
    [fqp_key]                                      UNIQUEIDENTIFIER CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_key] DEFAULT (newid()) NOT NULL,
    [fqp_is_active]                                BIT              CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_is_active] DEFAULT ((1)) NOT NULL,
    [fqp_created_by]                               NVARCHAR (128)   NOT NULL,
    [fqp_created_by_name]                          VARCHAR (300)    NULL,
    [fqp_created_date]                             DATETIME         CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_created_date] DEFAULT (getdate()) NOT NULL,
    [fqp_modified_by]                              NVARCHAR (128)   NULL,
    [fqp_modified_by_name]                         VARCHAR (300)    NULL,
    [fqp_modified_date]                            DATETIME         NULL,
    [fqp_volume_ed_visits]                         INT              NULL,
    [fqp_volume_go_live_annual_strokes]            INT              NULL,
    [fqp_volume_go_live_ip_neuro_per_day]          INT              NULL,
    [fqp_volume_go_live_EEG_per_month]             INT              NULL,
    [fqp_op_emergency_neuro]                       NVARCHAR (MAX)   NULL,
    [fqp_op_general_neuro]                         NVARCHAR (MAX)   NULL,
    [fqp_op_EEG]                                   NVARCHAR (MAX)   NULL,
    [fqp_op_EGG_equipment]                         NVARCHAR (500)   NULL,
    [fqp_op_ct_cta_schedule]                       NVARCHAR (MAX)   NULL,
    [fqp_op_mri_schedule]                          NVARCHAR (MAX)   NULL,
    [fqp_op_radiology_coverage_for_stroke]         NVARCHAR (MAX)   NULL,
    [fqp_op_nir]                                   NVARCHAR (MAX)   NULL,
    [fqp_op_weighted_stretchers]                   NVARCHAR (MAX)   NULL,
    [fqp_process_ed_stroke_desc]                   NVARCHAR (MAX)   NULL,
    [fqp_process_stat_response]                    NVARCHAR (MAX)   NULL,
    [fqp_process_timeframe_code_stroke]            NVARCHAR (MAX)   NULL,
    [fqp_process_admin_post_tpa_patients]          NVARCHAR (MAX)   NULL,
    [fqp_process_rn_nihss_certified]               BIT              NOT NULL,
    [fqp_process_facility_transfer_patient_stroke] VARCHAR (150)    NULL,
    [fqp_bedsize]                                  INT              NULL,
    [fqp_service_has_telestroke]                   BIT              CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_service_has_telestroke] DEFAULT ((0)) NOT NULL,
    [fqp_service_has_teleneuro]                    BIT              CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_service_has_teleneuro] DEFAULT ((0)) NOT NULL,
    [fqp_service_has_stat_consult]                 BIT              CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_service_has_stat_consult] DEFAULT ((0)) NOT NULL,
    [fqp_service_has_eeg]                          BIT              CONSTRAINT [DF_facility_questionnaire_pre_live_fqp_service_has_eeg] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_facility_questionnaire_pre_live] PRIMARY KEY CLUSTERED ([fqp_key] ASC),
    CONSTRAINT [FK_facility_questionnaire_pre_live_facility] FOREIGN KEY ([fqp_key]) REFERENCES [dbo].[facility] ([fac_key])
);

