CREATE TABLE [dbo].[MDStaffFacility] (
    [ID]                VARCHAR (128) NOT NULL,
    [ReferenceSourceID] VARCHAR (128) NOT NULL,
    [ReferenceType]     VARCHAR (128) NULL,
    [Code]              VARCHAR (128) NULL,
    [Name]              VARCHAR (500) NULL,
    [Address]           VARCHAR (500) NULL,
    [Address2]          VARCHAR (500) NULL,
    [City]              VARCHAR (500) NULL,
    [State]             VARCHAR (50)  NULL,
    [Zip]               VARCHAR (50)  NULL,
    [Telephone]         VARCHAR (50)  NULL,
    [Fax]               VARCHAR (50)  NULL,
    [Email]             VARCHAR (500) NULL,
    [URL]               VARCHAR (500) NULL,
    [LastUpdated]       VARCHAR (50)  NULL,
    [UpdatedBy]         VARCHAR (100) NULL,
    [Comments]          VARCHAR (MAX) NULL,
    [Country]           VARCHAR (50)  NULL,
    [County]            VARCHAR (50)  NULL,
    [TaxID]             VARCHAR (50)  NULL,
    [Manager]           VARCHAR (300) NULL,
    [Uid]               VARCHAR (128) NULL,
    [Type]              VARCHAR (50)  NULL,
    [CountryID]         VARCHAR (128) NULL,
    [CountyID]          VARCHAR (128) NULL,
    [TypesList]         VARCHAR (300) NULL,
    [AddressBlock]      VARCHAR (300) NULL,
    [IsArchived]        BIT           NULL,
    [IsNew]             BIT           NULL,
    [IsLoaded]          BIT           NULL,
    [ImportDateUTC]     DATETIME      CONSTRAINT [DF_MDStaffFacility_ImportDateUTC] DEFAULT (getutcdate()) NOT NULL
);

