CREATE TABLE [dbo].[post_acute_care] (
    [pac_key]                              INT              IDENTITY (1, 1) NOT NULL,
    [pac_ctp_key]                          INT              NULL,
    [pac_fac_key]                          UNIQUEIDENTIFIER NULL,
    [pac_phy_key]                          NVARCHAR (128)   NULL,
    [pac_cst_key]                          INT              NULL,
    [pac_notes]                            VARCHAR (MAX)    NULL,
    [pac_patient]                          VARCHAR (300)    NULL,
    [pac_patient_initials]                 VARCHAR (50)     NULL,
    [pac_case_number]                      BIGINT           NULL,
    [pac_callback]                         VARCHAR (50)     NULL,
    [pac_cart]                             NVARCHAR (50)    NULL,
    [pac_date_of_consult]                  DATETIME         NULL,
    [pac_time_of_consult]                  DATETIME         NULL,
    [pac_dob]                              DATETIME         NULL,
    [pac_caller]                           NVARCHAR (128)   NULL,
    [pac_identification_number]            VARCHAR (50)     NULL,
    [pac_identification_type]              INT              NULL,
    [pac_referring_physician]              NVARCHAR (128)   NULL,
    [pac_billing_bic_key]                  INT              NULL,
    [pac_is_active]                        BIT              NOT NULL,
    [pac_billing_diagnosis]                VARCHAR (MAX)    NULL,
    [pac_followup_case_key]                INT              NULL,
    [pac_is_phy_blast]                     BIT              NULL,
    [pac_created_by]                       NVARCHAR (128)   NULL,
    [pac_created_by_name]                  NVARCHAR (128)   NULL,
    [pac_created_date]                     DATETIME         NULL,
    [pac_modified_by]                      NVARCHAR (128)   NULL,
    [pac_modified_date]                    DATETIME         NULL,
    [pac_ruleoutacuteischemicstroke]       BIT              NULL,
    [pac_largevesselinfract]               BIT              NULL,
    [pac_levelofconsciousness]             INT              NULL,
    [pac_mechanismofstroke]                NVARCHAR (MAX)   NULL,
    [pac_pulse]                            NVARCHAR (MAX)   NULL,
    [pac_billing_date_of_consult]          DATETIME         NULL,
    [pac_billing_patient_name]             VARCHAR (300)    NULL,
    [pac_billing_dob]                      DATETIME         NULL,
    [pac_billing_visit_type]               VARCHAR (20)     NULL,
    [pac_follow_up_date]                   DATE             NULL,
    [pac_billing_notes]                    VARCHAR (MAX)    NULL,
    [pac_billing_comments]                 VARCHAR (MAX)    NULL,
    [pac_billing_physician_blast_date]     DATETIME         NULL,
    [pac_billing_physician_blast_date_est] DATETIME         NULL,
    [pac_billing_physician_blast]          BIT              NULL,
    [pac_hh_nurse]                         VARCHAR (MAX)    NULL,
    [pac_hh_contact]                       VARCHAR (MAX)    NULL,
    [pac_date_of_completion]               DATETIME         NULL,
    [pac_seen_by_telespecialist]           INT              NULL,
    [pac_seen_type]                        VARCHAR (100)    NULL,
    [pac_gender]                           VARCHAR (20)     NULL,
    [pac_chief_complaint]                  NVARCHAR (MAX)   NULL,
    [pac_hpi]                              NVARCHAR (MAX)   NULL,
    [pac_pmh]                              NVARCHAR (MAX)   NULL,
    [pac_ros]                              NVARCHAR (MAX)   NULL,
    [pac_impression]                       NVARCHAR (MAX)   NULL,
    [pac_plan]                             NVARCHAR (MAX)   NULL,
    [pac_home_healthplan]                  INT              NULL,
    [pac_home_healthnurse]                 INT              NULL,
    [pac_patients_laboratory]              INT              NULL,
    [pac_patients_imaging]                 INT              NULL,
    [pac_patients_medicationlist]          INT              NULL,
    [pac_patients_treatmentplan]           INT              NULL,
    [pac_reviewing_patientdata]            INT              NULL,
    [pac_pb]                               NVARCHAR (250)   NULL,
    [pac_temp]                             NVARCHAR (250)   NULL,
    [pac_respirations]                     NVARCHAR (250)   NULL,
    [pac_awake]                            INT              NULL,
    [pac_acute_distress]                   INT              NULL,
    [pac_appears_age]                      INT              NULL,
    [pac_normocephalic]                    INT              NULL,
    [pac_atraumatic]                       INT              NULL,
    [pac_perrl_or_unequalpupils]           INT              NULL,
    [pac_intact_or_impaired]               INT              NULL,
    [pac_trachea_midline]                  INT              NULL,
    [pac_neck_jvd]                         INT              NULL,
    [pac_neck_masses]                      INT              NULL,
    [pac_gi_abdomen]                       INT              NULL,
    [pac_extremities_spontaneously]        INT              NULL,
    [pac_range_of_motion]                  INT              NULL,
    [pac_clubbing]                         INT              NULL,
    [pac_cyanosis]                         INT              NULL,
    [pac_swelling_or_edema]                INT              NULL,
    [pac_varicosities]                     INT              NULL,
    [pac_neuro_oriented]                   INT              NULL,
    [pac_neuro_time]                       INT              NULL,
    [pac_neuro_place]                      INT              NULL,
    [pac_neuro_person]                     INT              NULL,
    [pac_neuro_cn_right]                   INT              NULL,
    [pac_neuro_cn_left]                    INT              NULL,
    [pac_neuro_cn]                         INT              NULL,
    [pac_speech]                           INT              NULL,
    [pac_tongue_midline]                   INT              NULL,
    [pac_exam_free_text]                   NVARCHAR (MAX)   NULL,
    [pac_billing_identification_number]    VARCHAR (50)     NULL,
    [pac_billing_identification_type]      INT              NULL,
    [pac_primary_discharge_diagnosis]      VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_home_health_users_case] PRIMARY KEY CLUSTERED ([pac_key] ASC),
    CONSTRAINT [FK_post_acute_care_facility] FOREIGN KEY ([pac_fac_key]) REFERENCES [dbo].[facility] ([fac_key]),
    CONSTRAINT [FK_post_acute_care_users_AspNetUsers] FOREIGN KEY ([pac_phy_key]) REFERENCES [dbo].[AspNetUsers] ([Id])
);


GO
ALTER TABLE [dbo].[post_acute_care] NOCHECK CONSTRAINT [FK_post_acute_care_facility];


GO
ALTER TABLE [dbo].[post_acute_care] NOCHECK CONSTRAINT [FK_post_acute_care_users_AspNetUsers];

