//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_setting
    {
        public int als_key { get; set; }
        public string als_phy_key { get; set; }
        public string als_audio_path { get; set; }
        public string als_selected_audio { get; set; }
        public string als_file_name { get; set; }
        public string als_created_by { get; set; }
        public string als_created_by_name { get; set; }
        public Nullable<System.DateTime> als_created_date { get; set; }
        public string als_modified_by { get; set; }
        public string als_modified_by_name { get; set; }
        public Nullable<System.DateTime> als_modified_date { get; set; }
        public Nullable<int> als_ent_key { get; set; }
    }
}
