//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_tunes
    {
        public int alt_key { get; set; }
        public string alt_phy_key { get; set; }
        public string alt_audio_path { get; set; }
        public string alt_selected_audio { get; set; }
        public string alt_file_name { get; set; }
        public string alt_created_by { get; set; }
        public string alt_created_by_name { get; set; }
        public Nullable<System.DateTime> alt_created_date { get; set; }
        public string alt_modified_by { get; set; }
        public string alt_modified_by_name { get; set; }
        public Nullable<System.DateTime> alt_modified_date { get; set; }
        public Nullable<int> alt_ent_key { get; set; }
    }
}
