//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_setting
    {
        public System.Guid aps_key { get; set; }
        public string aps_md_login { get; set; }
        public string aps_md_password { get; set; }
        public string aps_md_instance { get; set; }
        public string aps_md_facility { get; set; }
        public string aps_md_grant_type { get; set; }
        public string aps_md_base_url { get; set; }
        public string aps_md_token_url { get; set; }
        public bool aps_enable_auto_assign_process { get; set; }
        public string aps_physician_role_id { get; set; }
        public string aps_csv_connection_string { get; set; }
        public bool aps_is_md_staff_active { get; set; }
        public System.DateTime aps_md_staff_last_run { get; set; }
        public string aps_modified_by { get; set; }
        public Nullable<System.DateTime> aps_modified_date { get; set; }
        public bool aps_cas_facility_popup_on_load { get; set; }
        public bool aps_security_is_lowercase_required { get; set; }
        public bool aps_security_is_uppercase_required { get; set; }
        public bool aps_security_is_number_required { get; set; }
        public bool aps_security_is_non_alphanumeric_required { get; set; }
        public Nullable<decimal> aps_security_password_length_value { get; set; }
        public int aps_security_password_age_value { get; set; }
        public Nullable<decimal> aps_security_password_history_value { get; set; }
        public bool aps_secuirty_is_reset_password_required { get; set; }
        public bool aps_secuirty_is_multi_factor_authentication_required { get; set; }
        public string aps_five9_domain { get; set; }
        public string aps_five9_number_to_dial { get; set; }
        public Nullable<int> aps_duplicate_popup_timer { get; set; }
        public bool aps_enable_case_auto_save { get; set; }
        public Nullable<System.DateTime> aps_clear_pending_cases_date { get; set; }
        public Nullable<System.TimeSpan> aps_statusgrid_filter_start_time { get; set; }
        public Nullable<System.TimeSpan> aps_statusgrid_filter_endtime { get; set; }
        public Nullable<System.DateTime> aps_clear_physician_pending_cases_date { get; set; }
        public Nullable<System.DateTime> aps_clear_physician_cta_cases_date { get; set; }
        public bool aps_enable_alarm_setting { get; set; }
        public string aps_audio_file_path { get; set; }
        public string aps_selected_audio { get; set; }
        public Nullable<bool> aps_tune_is_active { get; set; }
        public string aps_rapids_email { get; set; }
        public string aps_rapids_password { get; set; }
        public string aps_rapids_service { get; set; }
        public System.TimeSpan aps_rapids_retention { get; set; }
        public int aps_status_page_interval { get; set; }
        public bool aps_enable_snooze_alarm_setting { get; set; }
        public string aps_snooze_audio_file_path { get; set; }
        public string aps_snooze_selected_audio { get; set; }
        public bool aps_snooze_tune_is_active { get; set; }
        public string aps_five9_list { get; set; }
        public Nullable<int> aps_eAlert_retry_limt { get; set; }
        public Nullable<long> aps_session_timeout_in_minutes { get; set; }
        public Nullable<long> aps_two_factor_code_expiry_timeout_in_minutes { get; set; }
        public bool aps_enable_logout_from_other_devices { get; set; }
        public Nullable<bool> aps_enable_pending_cases_notifications { get; set; }
    }
}
