//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_records
    {
        public int aud_key { get; set; }
        public string aud_username { get; set; }
        public string aud_action { get; set; }
        public Nullable<System.DateTime> aud_timestamp { get; set; }
        public string aud_browser { get; set; }
        public string aud_ip_address { get; set; }
        public string aud_host_name { get; set; }
        public string aud_others { get; set; }
    }
}
