//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCI_ReportData
    {
        public int BCI_ID { get; set; }
        public string Phy_Name { get; set; }
        public string Phy_Bci_Value { get; set; }
        public string Phy_Id { get; set; }
    }
}
