//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_history
    {
        public int chi_key { get; set; }
        public string chi_call_id { get; set; }
        public string chi_call_object_id { get; set; }
        public string chi_ani { get; set; }
        public string chi_campaign_name { get; set; }
        public string chi_campaign_id { get; set; }
        public string chi_dnis { get; set; }
        public string chi_domain_name { get; set; }
        public string chi_customer { get; set; }
        public Nullable<System.DateTime> chi_start_time_stamp { get; set; }
        public string chi_agent { get; set; }
        public string chi_agent_extension { get; set; }
        public string chi_agent_name { get; set; }
        public string chi_call_result { get; set; }
        public string chi_call_type { get; set; }
        public string chi_call_back_id { get; set; }
        public string chi_call_back_number { get; set; }
        public string chi_comments { get; set; }
        public Nullable<int> chi_duration { get; set; }
        public string chi_format_api_call_type { get; set; }
        public Nullable<System.DateTime> chi_handle_time { get; set; }
        public string chi_session_id { get; set; }
        public string chi_subject { get; set; }
        public Nullable<int> chi_talk_and_hold_duration { get; set; }
        public Nullable<System.DateTime> chi_wrap_time { get; set; }
        public bool chi_is_active { get; set; }
        public string chi_created_by { get; set; }
        public System.DateTime chi_created_date { get; set; }
        public string chi_modified_by { get; set; }
        public Nullable<System.DateTime> chi_modified_date { get; set; }
        public string chi_original_stamp_time { get; set; }
    }
}
