//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_template_stroke_neuro_tpa
    {
        public int csn_cas_key { get; set; }
        public string csn_impression { get; set; }
        public string csn_acute_stroke { get; set; }
        public string csn_mechanism_stroke { get; set; }
        public string csn_mechanism_stroke_text { get; set; }
        public Nullable<int> csn_tpa_bolus_complications { get; set; }
        public string csn_tpa_bolus_complications_text { get; set; }
        public Nullable<int> csn_nihss_totalscore { get; set; }
        public string csn_vitals_bp { get; set; }
        public string csn_vitals_pulse { get; set; }
        public string csn_verbal_consent { get; set; }
        public string csn_additional_recomendations { get; set; }
        public System.DateTime csn_created_date { get; set; }
        public string csn_created_by { get; set; }
        public string csn_created_by_name { get; set; }
        public string csn_modified_by { get; set; }
        public string csn_modfied_by_name { get; set; }
        public Nullable<System.DateTime> csn_modified_date { get; set; }
        public string csn_comment { get; set; }
        public string csn_vitals_blood_glucose { get; set; }
        public Nullable<bool> csn_patient_family_cosulted { get; set; }
        public Nullable<bool> csn_critical_care_was_provided { get; set; }
        public Nullable<int> csn_critical_care_minutes { get; set; }
        public Nullable<bool> csn_family_consent_available { get; set; }
        public string csn_PMH { get; set; }
        public Nullable<bool> csn_anticoagulant_use { get; set; }
        public string csn_anticoagulant_use_text { get; set; }
        public Nullable<bool> csn_antiplatelet_use { get; set; }
        public string csn_antiplatelet_use_text { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
