//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_generated_template
    {
        public int cgt_key { get; set; }
        public int cgt_cas_key { get; set; }
        public string cgt_template_html { get; set; }
        public Nullable<System.DateTime> cgt_finalize_date { get; set; }
        public System.DateTime cgt_created_date { get; set; }
        public string cgt_created_by { get; set; }
        public string cgt_created_by_name { get; set; }
        public Nullable<System.DateTime> cgt_modified_date { get; set; }
        public string cgt_modified_by { get; set; }
        public string cgt_modified_by_name { get; set; }
        public int cgt_ent_key { get; set; }
    
        public virtual entity_type entity_type { get; set; }
        public virtual @case @case { get; set; }
    }
}
