//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_timestamp
    {
        public int cts_cas_key { get; set; }
        public Nullable<System.DateTime> cts_waiting_to_accept_est { get; set; }
        public Nullable<System.DateTime> cts_waiting_to_accept_utc { get; set; }
        public Nullable<System.DateTime> cts_accepted_est { get; set; }
        public Nullable<System.DateTime> cts_accepted_utc { get; set; }
        public Nullable<long> cts_waiting_to_accept_accept_sec { get; set; }
        public Nullable<long> cts_arrival_to_needle_sec { get; set; }
        public Nullable<long> cts_physician_mdm_sec { get; set; }
        public Nullable<long> cts_response_sec { get; set; }
        public Nullable<long> cts_symptom_to_needle_sec { get; set; }
        public Nullable<long> cts_last_known_well_to_needle_sec { get; set; }
        public Nullable<long> cts_bedside_response_sec { get; set; }
        public Nullable<long> cts_start_to_stamp_sec { get; set; }
        public Nullable<long> cts_start_to_accept_sec { get; set; }
        public Nullable<long> cts_arrival_to_stamp_sec { get; set; }
        public Nullable<long> cts_arrival_to_start_sec { get; set; }
        public Nullable<long> cts_cpoe_order_to_needle { get; set; }
        public Nullable<long> cts_login_to_handle_sec { get; set; }
        public Nullable<long> cts_on_screen_sec { get; set; }
        public Nullable<long> cts_verbal_order_to_cpoe_sec { get; set; }
        public Nullable<long> cts_verbal_order_to_needle_sec { get; set; }
        public Nullable<System.DateTime> cts_created_date { get; set; }
        public string cts_created_by { get; set; }
        public Nullable<System.DateTime> cts_modified_date { get; set; }
        public string cts_modified_by { get; set; }
        public Nullable<long> cts_callback_to_tsnotification { get; set; }
    }
}
