//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_review_template
    {
        public int crt_key { get; set; }
        public Nullable<int> crt_cas_key { get; set; }
        public string crt_template_html { get; set; }
        public Nullable<System.DateTime> crt_finalize_date { get; set; }
        public Nullable<System.DateTime> crt_created_date { get; set; }
        public string crt_created_by { get; set; }
        public string crt_created_by_name { get; set; }
        public Nullable<System.DateTime> crt_modified_date { get; set; }
        public string crt_modified_by { get; set; }
        public string crt_modified_by_name { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
