//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_template_stroke_notpa
    {
        public int ctn_cas_key { get; set; }
        public string ctn_impression { get; set; }
        public string ctn_impression_text { get; set; }
        public string ctn_mechanism_stroke { get; set; }
        public string ctn_mechanism_stroke_text { get; set; }
        public string ctn_comment { get; set; }
        public string ctn_antiplatelet_therapy_recommedned { get; set; }
        public string ctn_antiplatelet_therapy_recommedned_text { get; set; }
        public string ctn_imaging_studies_recommedned { get; set; }
        public string ctn_imaging_studies_recommedned_text { get; set; }
        public string ctn_therapies { get; set; }
        public Nullable<int> ctn_nihss_totalscore { get; set; }
        public string ctn_dysphaghia_screen { get; set; }
        public string ctn_dvt_prophylaxis { get; set; }
        public string ctn_dvt_prophylaxis_text { get; set; }
        public bool ctn_lipid_panel_obtained { get; set; }
        public Nullable<int> ctn_disposition { get; set; }
        public string ctn_sign_out { get; set; }
        public System.DateTime ctn_created_date { get; set; }
        public string ctn_created_by { get; set; }
        public string ctn_created_by_name { get; set; }
        public string ctn_modified_by { get; set; }
        public string ctn_modfied_by_name { get; set; }
        public Nullable<System.DateTime> ctn_modified_date { get; set; }
        public string ctn_vitals_bp { get; set; }
        public string ctn_vitals_pulse { get; set; }
        public string ctn_vitals_blood_glucose { get; set; }
        public Nullable<bool> ctn_patient_family_cosulted { get; set; }
        public Nullable<bool> ctn_critical_care_was_provided { get; set; }
        public Nullable<int> ctn_critical_care_minutes { get; set; }
        public Nullable<bool> ctn_family_consent_available { get; set; }
        public string ctn_PMH { get; set; }
        public Nullable<bool> ctn_anticoagulant_use { get; set; }
        public string ctn_anticoagulant_use_text { get; set; }
        public Nullable<bool> ctn_antiplatelet_use { get; set; }
        public string ctn_antiplatelet_use_text { get; set; }
        public Nullable<int> ctn_NIHSS_comatose { get; set; }
        public string ctn_NIHSS_comatose_text { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
