//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_template_stroke_tpa
    {
        public int cts_cas_key { get; set; }
        public string cts_impression { get; set; }
        public string cts_acute_stroke { get; set; }
        public string cts_mechanism_stroke { get; set; }
        public string cts_mechanism_stroke_text { get; set; }
        public Nullable<int> cts_tpa_bolus_complications { get; set; }
        public string cts_tpa_bolus_complications_text { get; set; }
        public Nullable<int> cts_nihss_totalscore { get; set; }
        public string cts_vitals_bp { get; set; }
        public string cts_vitals_pulse { get; set; }
        public string cts_verbal_consent { get; set; }
        public System.DateTime cts_created_date { get; set; }
        public string cts_created_by { get; set; }
        public string cts_created_by_name { get; set; }
        public string cts_modified_by { get; set; }
        public string cts_modfied_by_name { get; set; }
        public Nullable<System.DateTime> cts_modified_date { get; set; }
        public string cts_comment { get; set; }
        public string cts_vitals_blood_glucose { get; set; }
        public Nullable<bool> cts_patient_family_cosulted { get; set; }
        public Nullable<bool> cts_critical_care_was_provided { get; set; }
        public Nullable<int> cts_critical_care_minutes { get; set; }
        public Nullable<bool> cts_family_consent_available { get; set; }
        public string cts_PMH { get; set; }
        public Nullable<bool> cts_anticoagulant_use { get; set; }
        public string cts_anticoagulant_use_text { get; set; }
        public Nullable<bool> cts_antiplatelet_use { get; set; }
        public string cts_antiplatelet_use_text { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
