//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_assign_history
    {
        public int cah_key { get; set; }
        public string cah_action { get; set; }
        public int cah_cas_key { get; set; }
        public string cah_phy_key { get; set; }
        public Nullable<System.DateTime> cah_request_sent_time { get; set; }
        public Nullable<System.DateTime> cah_action_time { get; set; }
        public Nullable<int> cah_sort_order { get; set; }
        public bool cah_is_active { get; set; }
        public System.DateTime cah_created_date { get; set; }
        public string cah_created_by { get; set; }
        public Nullable<System.DateTime> cah_modified_date { get; set; }
        public string cah_modified_by { get; set; }
        public bool cah_is_manuall_assign { get; set; }
        public Nullable<System.DateTime> cah_request_sent_time_utc { get; set; }
        public Nullable<System.DateTime> cah_action_time_utc { get; set; }
        public Nullable<System.DateTime> cah_created_date_utc { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
