//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class component_access
    {
        public int cac_key { get; set; }
        public string cac_roleid { get; set; }
        public Nullable<int> cac_com_key { get; set; }
        public string cac_addedby { get; set; }
        public Nullable<System.DateTime> cac_addeddate { get; set; }
        public string cac_modifiedby { get; set; }
        public Nullable<System.DateTime> cac_modifiedon { get; set; }
        public bool cac_isAllowed { get; set; }
    
        public virtual component component { get; set; }
    }
}
