//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class default_notification_tune
    {
        public int dnt_key { get; set; }
        public string dnt_file_path { get; set; }
        public string dnt_selected_tune { get; set; }
        public string dnt_created_by { get; set; }
        public string dnt_created_by_name { get; set; }
        public Nullable<System.DateTime> dnt_created_date { get; set; }
        public string dnt_modified_by { get; set; }
        public string dnt_modified_by_name { get; set; }
        public Nullable<System.DateTime> dnt_modified_date { get; set; }
        public Nullable<bool> dnt_is_active { get; set; }
    }
}
