//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ealert_user_case_type
    {
        public int ect_key { get; set; }
        public int ect_case_type_key { get; set; }
        public string ect_user_key { get; set; }
        public bool ect_is_active { get; set; }
        public bool ect_is_default { get; set; }
        public string ect_created_by { get; set; }
        public string ect_created_by_name { get; set; }
        public System.DateTime ect_created_date { get; set; }
        public string ect_modified_by { get; set; }
        public string ect_modified_by_name { get; set; }
        public Nullable<System.DateTime> ect_modified_date { get; set; }
    
        public virtual ucl_data ucl_data { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
