//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ealert_user_facility
    {
        public int efa_key { get; set; }
        public System.Guid efa_fac_key { get; set; }
        public string efa_user_key { get; set; }
        public bool efa_is_active { get; set; }
        public bool efa_is_default { get; set; }
        public string efa_created_by { get; set; }
        public string efa_created_by_name { get; set; }
        public System.DateTime efa_created_date { get; set; }
        public string efa_modified_by { get; set; }
        public string efa_modified_by_name { get; set; }
        public Nullable<System.DateTime> efa_modified_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual facility facility { get; set; }
    }
}
