//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_change_log
    {
        public int ecl_key { get; set; }
        public string ecl_changeset { get; set; }
        public string ecl_created_by { get; set; }
        public string ecl_created_by_name { get; set; }
        public System.DateTime ecl_created_date { get; set; }
        public string ecl_entity_key { get; set; }
        public string ecl_type { get; set; }
    }
}
