//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity_note
    {
        public int etn_key { get; set; }
        public string etn_notes { get; set; }
        public bool etn_is_active { get; set; }
        public string etn_created_by { get; set; }
        public System.DateTime etn_created_date { get; set; }
        public string etn_modified_by { get; set; }
        public Nullable<System.DateTime> etn_modified_date { get; set; }
        public string etn_entity_key { get; set; }
        public int etn_ntt_key { get; set; }
        public int etn_ent_key { get; set; }
        public bool etn_display_on_open { get; set; }
        public string etn_created_by_name { get; set; }
        public string etn_modified_by_name { get; set; }
    }
}
