//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facility()
        {
            this.cases = new HashSet<@case>();
            this.contacts = new HashSet<contact>();
            this.ealert_user_facility = new HashSet<ealert_user_facility>();
            this.post_acute_care = new HashSet<post_acute_care>();
            this.quality_goals = new HashSet<quality_goals>();
            this.facility_physician = new HashSet<facility_physician>();
        }
    
        public System.Guid fac_key { get; set; }
        public string fac_name { get; set; }
        public bool fac_is_active { get; set; }
        public string fac_created_by { get; set; }
        public System.DateTime fac_created_date { get; set; }
        public string fac_modified_by { get; set; }
        public Nullable<System.DateTime> fac_modified_date { get; set; }
        public string fac_address_line1 { get; set; }
        public string fac_address_line2 { get; set; }
        public string fac_city { get; set; }
        public Nullable<int> fac_stt_key { get; set; }
        public string fac_zip { get; set; }
        public string fac_timezone { get; set; }
        public Nullable<int> fac_fct_key { get; set; }
        public Nullable<int> fac_cst_key { get; set; }
        public Nullable<int> fac_sct_key { get; set; }
        public string fac_md_staff_source_name { get; set; }
        public string fac_md_staff_reference_source_id { get; set; }
        public string fac_created_by_name { get; set; }
        public string fac_modified_by_name { get; set; }
        public bool fac_not_templated_used { get; set; }
        public bool fac_go_live { get; set; }
        public string qps_number { get; set; }
        public string fac_emr { get; set; }
        public bool fac_is_pac { get; set; }
        public Nullable<int> fac_ucd_key_system { get; set; }
        public Nullable<int> fac_ucd_region_key { get; set; }
        public Nullable<System.Guid> fac_freestanding_fac_key { get; set; }
        public string fac_emr_portal { get; set; }
        public string fac_cart_type { get; set; }
        public string fac_transfer_process { get; set; }
        public string fac_ai_software { get; set; }
        public string fac_tpa_orderset { get; set; }
        public string fac_imaging_protocol { get; set; }
        public Nullable<int> fac_ucd_bed_size { get; set; }
        public string fac_cart_numbers { get; set; }
        public string fac_cst_key_with_Name { get; set; }
        public bool IsSleep { get; set; }
        public string fac_ts_account_ID { get; set; }
        public string fac_description { get; set; }
        public string fac_system { get; set; }
        public Nullable<int> fac_ai_software_ddl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@case> cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ealert_user_facility> ealert_user_facility { get; set; }
        public virtual facility_contract facility_contract { get; set; }
        public virtual facility_questionnaire_pre_live facility_questionnaire_pre_live { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_acute_care> post_acute_care { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quality_goals> quality_goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facility_physician> facility_physician { get; set; }
    }
}
