//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_physician
    {
        public int fap_key { get; set; }
        public System.Guid fap_fac_key { get; set; }
        public string fap_user_key { get; set; }
        public bool fap_is_active { get; set; }
        public System.DateTime fap_created_date { get; set; }
        public string fap_created_by { get; set; }
        public Nullable<System.DateTime> fap_modified_date { get; set; }
        public string fap_modified_by { get; set; }
        public Nullable<System.DateTime> fap_start_date { get; set; }
        public Nullable<System.DateTime> fap_end_date { get; set; }
        public bool fap_is_on_boarded { get; set; }
        public string fap_created_by_name { get; set; }
        public string fap_modified_by_name { get; set; }
        public bool fap_is_override { get; set; }
        public Nullable<System.DateTime> fap_override_start { get; set; }
        public Nullable<int> fap_override_hours { get; set; }
        public Nullable<System.DateTime> fap_onboarding_complete_provider_active_date { get; set; }
        public bool fap_is_hide_pending_onboarding { get; set; }
        public Nullable<System.DateTime> fap_onboarded_date { get; set; }
        public string fap_onboarded_by { get; set; }
        public string fap_onboarded_by_name { get; set; }
        public bool fap_hide { get; set; }
        public string fap_credential_specialist { get; set; }
        public string fap_app_specialist { get; set; }
        public Nullable<System.DateTime> fap_date_assigned { get; set; }
        public Nullable<System.DateTime> fap_initial_app_received { get; set; }
        public Nullable<System.DateTime> fap_app_started { get; set; }
        public Nullable<System.DateTime> fap_app_submitted_to_hospital { get; set; }
        public Nullable<System.DateTime> fap_vcaa_date { get; set; }
        public Nullable<System.DateTime> fap_anticipated_start { get; set; }
        public Nullable<System.DateTime> fap_preapp_request_date { get; set; }
        public Nullable<System.DateTime> fap_preapp_submitted_date { get; set; }
        public Nullable<System.DateTime> fap_preapp_receive_date { get; set; }
        public Nullable<System.DateTime> fap_app_sent_to_dr { get; set; }
        public Nullable<System.DateTime> fap_Credentials_confirmed_date { get; set; }
        public string fap_Password { get; set; }
        public string fap_Password_BY { get; set; }
        public Nullable<System.DateTime> fap_Password_Date { get; set; }
        public string fap_Array_path { get; set; }
        public string fap_UserName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual facility facility { get; set; }
    }
}
