//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facility_contract()
        {
            this.facility_contract_service = new HashSet<facility_contract_service>();
        }
    
        public System.Guid fct_key { get; set; }
        public Nullable<System.DateTime> fct_start_date { get; set; }
        public Nullable<System.DateTime> fct_end_date { get; set; }
        public int fct_cvr_key { get; set; }
        public System.DateTime fct_created_date { get; set; }
        public string fct_created_by { get; set; }
        public Nullable<System.DateTime> fct_modified_date { get; set; }
        public string fct_modified_by { get; set; }
        public bool fct_is_active { get; set; }
        public string fct_service_calc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facility_contract_service> facility_contract_service { get; set; }
        public virtual facility facility { get; set; }
    }
}
