//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_questionnaire_contact
    {
        public int fqc_key { get; set; }
        public int fqc_fqd_key { get; set; }
        public string fqc_name { get; set; }
        public string fqc_phone { get; set; }
        public string fqc_email { get; set; }
        public System.Guid fqc_fqp_key { get; set; }
        public System.DateTime fqc_created_date { get; set; }
        public string fqc_created_by { get; set; }
        public string fqc_created_by_name { get; set; }
    
        public virtual facility_questionnaire_pre_live facility_questionnaire_pre_live { get; set; }
        public virtual facility_questionnaire_contact_designation facility_questionnaire_contact_designation { get; set; }
    }
}
