//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_rate
    {
        public int fct_key { get; set; }
        public System.Guid fct_facility_key { get; set; }
        public Nullable<int> fct_billing_key { get; set; }
        public Nullable<int> fct_starting { get; set; }
        public Nullable<int> fct_ending { get; set; }
        public string fct_range { get; set; }
        public Nullable<decimal> fct_rate { get; set; }
        public Nullable<System.DateTime> fct_start_date { get; set; }
        public Nullable<System.DateTime> fct_end_date { get; set; }
        public string fct_created_by { get; set; }
        public Nullable<System.DateTime> fct_created_date { get; set; }
        public string fct_created_by_name { get; set; }
        public string fct_modified_by { get; set; }
        public Nullable<System.DateTime> fct_modified_date { get; set; }
        public string fct_modified_by_name { get; set; }
    }
}
