//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_availability_rate
    {
        public int far_key { get; set; }
        public Nullable<System.Guid> far_fac_key { get; set; }
        public Nullable<int> far_shifts { get; set; }
        public Nullable<decimal> far_rate { get; set; }
        public Nullable<System.DateTime> far_start_date { get; set; }
        public Nullable<System.DateTime> far_end_date { get; set; }
        public bool far_recurrence { get; set; }
        public string far_created_by { get; set; }
        public Nullable<System.DateTime> far_created_date { get; set; }
        public string far_created_by_name { get; set; }
        public string far_modified_by { get; set; }
        public Nullable<System.DateTime> far_modified_date { get; set; }
        public string far_modified_by_name { get; set; }
    }
}
