//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class firebase_users
    {
        public int frb_key { get; set; }
        public string frb_userId { get; set; }
        public string frb_user_firebaseId { get; set; }
        public string frb_deviceTokenId { get; set; }
    }
}
