//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class firebase_usersemail
    {
        public int fre_key { get; set; }
        public string fre_userId { get; set; }
        public string fre_firstname { get; set; }
        public string fre_lastname { get; set; }
        public string fre_email { get; set; }
        public string fre_firebase_email { get; set; }
        public string fre_firebase_uid { get; set; }
        public string fre_profileimg { get; set; }
    }
}
