//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forcast_Data
    {
        public int Id { get; set; }
        public string Fac_Id { get; set; }
        public string Fac_Name { get; set; }
        public Nullable<System.DateTime> Month_Name { get; set; }
        public string Month_Prediction { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
