//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class goals_data
    {
        public int gd_key { get; set; }
        public Nullable<int> gd_qag_key { get; set; }
        public string qag_door_to_TS_notification_ave_minutes { get; set; }
        public string qag_door_to_TS_notification_median_minutes { get; set; }
        public string qag_percent10_min_or_less_activation_EMS { get; set; }
        public string qag_percent10_min_or_less_activation_PV { get; set; }
        public string qag_percent10_min_or_less_activation_Inpt { get; set; }
        public string qag_TS_notification_to_response_average_minute { get; set; }
        public string qag_TS_notification_to_response_median_minute { get; set; }
        public string qag_percent_TS_at_bedside_grterthan10_minutes { get; set; }
        public string qag_alteplase_administered { get; set; }
        public string qag_door_to_needle_average { get; set; }
        public string qag_door_to_needle_median { get; set; }
        public string qag_verbal_order_to_administration_average_minutes { get; set; }
        public string qag_DTN_grter_or_equal_30minutes_percent { get; set; }
        public string qag_DTN_grter_or_equal_45minutes_percent { get; set; }
        public string qag_DTN_grter_or_equal_60minutes_percent { get; set; }
        public string qag_TS_notification_to_needle_grter_or_equal_30minutes_percent { get; set; }
        public string qag_TS_notification_to_needle_grter_or_equal_45minutes_percent { get; set; }
        public string qag_TS_notification_to_needle_grter_or_equal_60minutes_percent { get; set; }
        public string gd_quater { get; set; }
        public string qag_cpoe_order_to_needle_ave_min { get; set; }
        public string qag_cpoe_order_to_needle_med_min { get; set; }
    
        public virtual quality_goals quality_goals { get; set; }
    }
}
