//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_Protocols
    {
        public int ID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterName_Info { get; set; }
        public string ParameterName_Image { get; set; }
        public string Facility_Name { get; set; }
        public string Facility_Id { get; set; }
        public Nullable<System.DateTime> Parameter_Add_Date { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
