//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class icd10_billing_codes_calcualtor
    {
        public int Id { get; set; }
        public Nullable<int> cod_parent_id { get; set; }
        public string cod_name { get; set; }
        public string cod_class_name { get; set; }
        public Nullable<int> cod_sort_order { get; set; }
        public Nullable<bool> cod_is_active { get; set; }
        public Nullable<System.DateTime> cod_added_date { get; set; }
        public Nullable<System.DateTime> cod_modified_date { get; set; }
        public string cod_linked_id { get; set; }
    }
}
