//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDStaffFacility
    {
        public string ID { get; set; }
        public string ReferenceSourceID { get; set; }
        public string ReferenceType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string Comments { get; set; }
        public string Country { get; set; }
        public string County { get; set; }
        public string TaxID { get; set; }
        public string Manager { get; set; }
        public string Uid { get; set; }
        public string Type { get; set; }
        public string CountryID { get; set; }
        public string CountyID { get; set; }
        public string TypesList { get; set; }
        public string AddressBlock { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsLoaded { get; set; }
        public System.DateTime ImportDateUTC { get; set; }
    }
}
