//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mute_firebase_notification
    {
        public int mfn_key { get; set; }
        public string mfn_user_key { get; set; }
        public string mfn_firebase_uid { get; set; }
        public Nullable<System.DateTime> mfn_created_on { get; set; }
        public Nullable<System.DateTime> mfn_start_from { get; set; }
        public Nullable<System.DateTime> mfn_to_end { get; set; }
    }
}
