//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nih_stroke_scale_answer
    {
        public int nsa_key { get; set; }
        public int nsa_cas_key { get; set; }
        public int nsa_nss_key { get; set; }
        public string nsa_created_by { get; set; }
        public System.DateTime nsa_created_date { get; set; }
        public string nsa_created_by_name { get; set; }
        public Nullable<int> nsa_ent_key { get; set; }
    
        public virtual entity_type entity_type { get; set; }
        public virtual nih_stroke_scale nih_stroke_scale { get; set; }
        public virtual @case @case { get; set; }
    }
}
