//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nih_stroke_scale_question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nih_stroke_scale_question()
        {
            this.nih_stroke_scale = new HashSet<nih_stroke_scale>();
        }
    
        public int nsq_key { get; set; }
        public string nsq_title { get; set; }
        public string nsq_created_by { get; set; }
        public Nullable<System.DateTime> nsq_created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nih_stroke_scale> nih_stroke_scale { get; set; }
    }
}
