//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nih_stroke_scale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nih_stroke_scale()
        {
            this.nih_stroke_scale_answer = new HashSet<nih_stroke_scale_answer>();
        }
    
        public int nss_key { get; set; }
        public string nss_title { get; set; }
        public int nss_score { get; set; }
        public int nss_nsq_key { get; set; }
        public string nss_created_by { get; set; }
        public Nullable<System.DateTime> nss_created_date { get; set; }
        public bool nss_is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nih_stroke_scale_answer> nih_stroke_scale_answer { get; set; }
        public virtual nih_stroke_scale_question nih_stroke_scale_question { get; set; }
    }
}
