//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationOutlierNotificationLog
    {
        public int Id { get; set; }
        public string cas_case_number { get; set; }
        public string cas_case_type { get; set; }
        public string cas_case_color { get; set; }
        public Nullable<System.DateTime> cas_created_date { get; set; }
        public Nullable<System.DateTime> cas_modified_date { get; set; }
        public string cas_case_fac_name { get; set; }
        public string cas_case_assign_phy_initial { get; set; }
    }
}
