//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationsoutliersTemp
    {
        public int CaseKey { get; set; }
        public Nullable<long> CaseNumber { get; set; }
        public string CaseType { get; set; }
        public string StartTime { get; set; }
        public string FacilityName { get; set; }
        public string Physician { get; set; }
        public string TS_Response_Time_or_CallBack_Response_Time { get; set; }
    }
}
