//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pac_case_template
    {
        public int pct_key { get; set; }
        public Nullable<int> pct_pac_key { get; set; }
        public string pct_template_html { get; set; }
        public Nullable<System.DateTime> pct_finalize_date { get; set; }
        public Nullable<System.DateTime> pct_created_date { get; set; }
        public string pct_created_by { get; set; }
        public string pct_created_by_name { get; set; }
        public Nullable<System.DateTime> pct_modified_date { get; set; }
        public string pct_modified_by { get; set; }
        public string pct_modified_by_name { get; set; }
    
        public virtual post_acute_care post_acute_care { get; set; }
    }
}
