//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.cases = new HashSet<@case>();
        }
    
        public int pat_key { get; set; }
        public string pat_Account_Prefix { get; set; }
        public Nullable<int> pat_Account_Number { get; set; }
        public string pat_firstname { get; set; }
        public string pat_lastname { get; set; }
        public Nullable<System.DateTime> pat_dob { get; set; }
        public string pat_sex { get; set; }
        public string pat_mrn { get; set; }
        public System.Guid pat_fac_key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@case> cases { get; set; }
        public virtual facility facility { get; set; }
    }
}
