//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_percentage_rate
    {
        public int ppr_key { get; set; }
        public string ppr_phy_key { get; set; }
        public Nullable<int> ppr_shift_id { get; set; }
        public string ppr_shift_name { get; set; }
        public Nullable<decimal> ppr_percentage { get; set; }
        public string ppr_created_by { get; set; }
        public string ppr_created_by_name { get; set; }
        public Nullable<System.DateTime> ppr_created_date { get; set; }
        public string ppr_modified_by { get; set; }
        public string ppr_modified_by_name { get; set; }
        public Nullable<System.DateTime> ppr_modified_date { get; set; }
        public Nullable<System.DateTime> ppr_start_date { get; set; }
        public Nullable<System.DateTime> ppr_end_date { get; set; }
    }
}
