//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_rate
    {
        public int rat_key { get; set; }
        public string rat_phy_key { get; set; }
        public Nullable<int> rat_starting { get; set; }
        public Nullable<int> rat_ending { get; set; }
        public string rat_range { get; set; }
        public Nullable<decimal> rat_price { get; set; }
        public Nullable<int> rat_shift_hour { get; set; }
        public Nullable<int> rat_shift_id { get; set; }
        public string rat_shift_name { get; set; }
        public Nullable<int> rat_cas_id { get; set; }
        public string rat_created_by { get; set; }
        public Nullable<System.DateTime> rat_created_date { get; set; }
        public string rat_created_by_name { get; set; }
        public string rat_modified_by { get; set; }
        public Nullable<System.DateTime> rat_modified_date { get; set; }
        public string rat_modified_by_name { get; set; }
        public Nullable<System.DateTime> rat_start_date { get; set; }
        public Nullable<System.DateTime> rat_end_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
