//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public physician_status()
        {
            this.physician_status1 = new HashSet<physician_status>();
            this.physician_status_snooze_option = new HashSet<physician_status_snooze_option>();
            this.physician_status_snooze = new HashSet<physician_status_snooze>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int phs_key { get; set; }
        public string phs_name { get; set; }
        public string phs_description { get; set; }
        public string phs_color_code { get; set; }
        public Nullable<System.TimeSpan> phs_threshhold_time { get; set; }
        public int phs_sort_order { get; set; }
        public bool phs_is_active { get; set; }
        public bool phs_is_default { get; set; }
        public string phs_created_by { get; set; }
        public Nullable<System.DateTime> phs_created_date { get; set; }
        public string phs_modified_by { get; set; }
        public Nullable<System.DateTime> phs_modified_date { get; set; }
        public Nullable<int> phs_move_status_key { get; set; }
        public Nullable<System.TimeSpan> phs_move_threshhold_time { get; set; }
        public Nullable<int> phs_assignment_priority { get; set; }
        public bool phs_enable_snooze { get; set; }
        public Nullable<System.TimeSpan> phs_snooze_time { get; set; }
        public Nullable<int> phs_max_snooze_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician_status> physician_status1 { get; set; }
        public virtual physician_status physician_status2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician_status_snooze_option> physician_status_snooze_option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physician_status_snooze> physician_status_snooze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
