//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_holiday_rate
    {
        public int phr_key { get; set; }
        public string phr_phy_key { get; set; }
        public Nullable<System.DateTime> phr_date { get; set; }
        public Nullable<decimal> phr_rate { get; set; }
        public string phr_created_by { get; set; }
        public Nullable<System.DateTime> phr_created_date { get; set; }
        public string phr_created_by_name { get; set; }
        public string phr_modified_by { get; set; }
        public Nullable<System.DateTime> phr_modified_date { get; set; }
        public string phr_modified_by_name { get; set; }
        public Nullable<long> phr_uss_key { get; set; }
        public Nullable<int> phr_shift_key { get; set; }
    
        public virtual user_schedule user_schedule { get; set; }
    }
}
