//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_status_snooze
    {
        public int pss_key { get; set; }
        public int pss_phs_key { get; set; }
        public string pss_user_key { get; set; }
        public System.TimeSpan pss_snooze_time { get; set; }
        public bool pss_is_active { get; set; }
        public Nullable<System.DateTime> pss_processed_date { get; set; }
        public System.DateTime pss_created_date { get; set; }
        public string pss_created_by { get; set; }
        public string pss_createe_by_name { get; set; }
        public bool pss_is_latest_snooze { get; set; }
        public string pss_modified_by { get; set; }
        public string pss_modified_by_name { get; set; }
        public Nullable<System.DateTime> pss_modified_date { get; set; }
    
        public virtual physician_status physician_status { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
