//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_license
    {
        public System.Guid phl_key { get; set; }
        public string phl_license_number { get; set; }
        public Nullable<System.Guid> phl_license_type { get; set; }
        public Nullable<System.DateTime> phl_expired_date { get; set; }
        public string phl_user_key { get; set; }
        public System.DateTime phl_issued_date { get; set; }
        public bool phl_is_active { get; set; }
        public Nullable<System.DateTime> phl_created_date { get; set; }
        public string phl_created_by { get; set; }
        public Nullable<System.DateTime> phl_modified_date { get; set; }
        public string phl_modified_by { get; set; }
        public Nullable<int> phl_license_state { get; set; }
        public string phl_licensure_board_id { get; set; }
        public string phl_licensure_board_name { get; set; }
        public bool phl_is_in_use { get; set; }
        public string phl_created_by_name { get; set; }
        public string phl_modified_by_name { get; set; }
        public Nullable<System.DateTime> phl_date_assigned { get; set; }
        public Nullable<System.DateTime> phl_app_started { get; set; }
        public Nullable<System.DateTime> phl_app_submitted_to_board { get; set; }
        public Nullable<System.DateTime> phl_app_sent_to_provider { get; set; }
        public Nullable<System.Guid> phl_assigned_to_id { get; set; }
        public string phl_assigned_to_name { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
