//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician_status_log
    {
        public int psl_key { get; set; }
        public string psl_user_key { get; set; }
        public int psl_phs_key { get; set; }
        public string psl_status_name { get; set; }
        public Nullable<System.DateTime> psl_created_date { get; set; }
        public string psl_created_by { get; set; }
        public Nullable<System.DateTime> psl_start_date { get; set; }
        public Nullable<System.DateTime> psl_end_date { get; set; }
        public string psl_modified_by { get; set; }
        public Nullable<System.DateTime> psl_modified_date { get; set; }
        public Nullable<long> psl_uss_key { get; set; }
        public Nullable<int> psl_cas_key { get; set; }
        public string psl_comments { get; set; }
        public Nullable<System.Guid> psl_fac_key { get; set; }
    
        public virtual physician_status_log physician_status_log1 { get; set; }
        public virtual physician_status_log physician_status_log2 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
