//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_acute_care
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post_acute_care()
        {
            this.pac_case_template = new HashSet<pac_case_template>();
        }
    
        public int pac_key { get; set; }
        public Nullable<int> pac_ctp_key { get; set; }
        public Nullable<System.Guid> pac_fac_key { get; set; }
        public string pac_phy_key { get; set; }
        public Nullable<int> pac_cst_key { get; set; }
        public string pac_notes { get; set; }
        public string pac_patient { get; set; }
        public string pac_patient_initials { get; set; }
        public Nullable<long> pac_case_number { get; set; }
        public string pac_callback { get; set; }
        public string pac_cart { get; set; }
        public Nullable<System.DateTime> pac_date_of_consult { get; set; }
        public Nullable<System.DateTime> pac_time_of_consult { get; set; }
        public Nullable<System.DateTime> pac_dob { get; set; }
        public string pac_caller { get; set; }
        public string pac_identification_number { get; set; }
        public Nullable<int> pac_identification_type { get; set; }
        public string pac_referring_physician { get; set; }
        public Nullable<int> pac_billing_bic_key { get; set; }
        public bool pac_is_active { get; set; }
        public string pac_billing_diagnosis { get; set; }
        public Nullable<int> pac_followup_case_key { get; set; }
        public Nullable<bool> pac_is_phy_blast { get; set; }
        public string pac_created_by { get; set; }
        public string pac_created_by_name { get; set; }
        public Nullable<System.DateTime> pac_created_date { get; set; }
        public string pac_modified_by { get; set; }
        public Nullable<System.DateTime> pac_modified_date { get; set; }
        public Nullable<System.DateTime> pac_billing_date_of_consult { get; set; }
        public string pac_billing_patient_name { get; set; }
        public Nullable<System.DateTime> pac_billing_dob { get; set; }
        public string pac_billing_visit_type { get; set; }
        public Nullable<System.DateTime> pac_follow_up_date { get; set; }
        public string pac_billing_notes { get; set; }
        public string pac_billing_comments { get; set; }
        public Nullable<System.DateTime> pac_billing_physician_blast_date { get; set; }
        public Nullable<System.DateTime> pac_billing_physician_blast_date_est { get; set; }
        public Nullable<bool> pac_billing_physician_blast { get; set; }
        public string pac_hh_nurse { get; set; }
        public string pac_hh_contact { get; set; }
        public Nullable<System.DateTime> pac_date_of_completion { get; set; }
        public Nullable<int> pac_seen_by_telespecialist { get; set; }
        public string pac_seen_type { get; set; }
        public string pac_gender { get; set; }
        public string pac_chief_complaint { get; set; }
        public string pac_hpi { get; set; }
        public string pac_pmh { get; set; }
        public string pac_ros { get; set; }
        public string pac_impression { get; set; }
        public string pac_plan { get; set; }
        public Nullable<int> pac_home_healthplan { get; set; }
        public Nullable<int> pac_home_healthnurse { get; set; }
        public Nullable<int> pac_patients_laboratory { get; set; }
        public Nullable<int> pac_patients_imaging { get; set; }
        public Nullable<int> pac_patients_medicationlist { get; set; }
        public Nullable<int> pac_patients_treatmentplan { get; set; }
        public Nullable<int> pac_reviewing_patientdata { get; set; }
        public string pac_pb { get; set; }
        public string pac_pulse { get; set; }
        public string pac_temp { get; set; }
        public string pac_respirations { get; set; }
        public Nullable<int> pac_awake { get; set; }
        public Nullable<int> pac_acute_distress { get; set; }
        public Nullable<int> pac_appears_age { get; set; }
        public Nullable<int> pac_normocephalic { get; set; }
        public Nullable<int> pac_atraumatic { get; set; }
        public Nullable<int> pac_perrl_or_unequalpupils { get; set; }
        public Nullable<int> pac_intact_or_impaired { get; set; }
        public Nullable<int> pac_trachea_midline { get; set; }
        public Nullable<int> pac_neck_jvd { get; set; }
        public Nullable<int> pac_neck_masses { get; set; }
        public Nullable<int> pac_gi_abdomen { get; set; }
        public Nullable<int> pac_extremities_spontaneously { get; set; }
        public Nullable<int> pac_range_of_motion { get; set; }
        public Nullable<int> pac_clubbing { get; set; }
        public Nullable<int> pac_cyanosis { get; set; }
        public Nullable<int> pac_swelling_or_edema { get; set; }
        public Nullable<int> pac_varicosities { get; set; }
        public Nullable<int> pac_neuro_oriented { get; set; }
        public Nullable<int> pac_neuro_time { get; set; }
        public Nullable<int> pac_neuro_place { get; set; }
        public Nullable<int> pac_neuro_person { get; set; }
        public Nullable<int> pac_neuro_cn_right { get; set; }
        public Nullable<int> pac_neuro_cn_left { get; set; }
        public Nullable<int> pac_neuro_cn { get; set; }
        public Nullable<int> pac_speech { get; set; }
        public Nullable<int> pac_tongue_midline { get; set; }
        public string pac_exam_free_text { get; set; }
        public string pac_billing_identification_number { get; set; }
        public Nullable<int> pac_billing_identification_type { get; set; }
        public string pac_primary_discharge_diagnosis { get; set; }
        public Nullable<bool> pac_ruleoutacuteischemicstroke { get; set; }
        public Nullable<bool> pac_largevesselinfract { get; set; }
        public Nullable<int> pac_levelofconsciousness { get; set; }
        public string pac_mechanismofstroke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pac_case_template> pac_case_template { get; set; }
        public virtual facility facility { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
