//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class premorbid_correspondnce
    {
        public int Id { get; set; }
        public Nullable<int> pmc_cas_key { get; set; }
        public string pmc_cas_premorbid_patient_phone { get; set; }
        public Nullable<System.DateTime> pmc_cas_premorbid_datetime_of_contact { get; set; }
        public Nullable<int> pmc_cas_premorbid_spokewith { get; set; }
        public string pmc_cas_premorbid_comments { get; set; }
        public Nullable<int> pmc_cas_premorbid_successful_or_unsuccessful { get; set; }
        public string pmc_cas_premorbid_completedby { get; set; }
        public Nullable<int> pmc_cas_patient_satisfaction_video_experience { get; set; }
        public Nullable<int> pmc_cas_patient_satisfaction_communication { get; set; }
        public Nullable<int> pmc_cas_willing_todo_interview { get; set; }
        public Nullable<int> pmc_cas_consent_sent { get; set; }
        public Nullable<int> pmc_cas_consent_received { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
