//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rapids_mailbox
    {
        public int rpd_key { get; set; }
        public string rpd_uid { get; set; }
        public System.DateTime rpd_date { get; set; }
        public string rpd_from { get; set; }
        public string rpd_to { get; set; }
        public string rpd_subject { get; set; }
        public string rpd_body { get; set; }
        public int rpd_attachments { get; set; }
        public string rpd_attachment_html { get; set; }
        public string rpd_logs { get; set; }
        public bool rpd_is_read { get; set; }
        public string rpd_created_by { get; set; }
        public System.DateTime rpd_created_date { get; set; }
    }
}
