//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rca_counter_measure
    {
        public int rca_Id { get; set; }
        public int rca_key_id { get; set; }
        public string rca_root_cause { get; set; }
        public string rca_proposed_countermeasure { get; set; }
        public string rca_responsible_party { get; set; }
        public Nullable<System.DateTime> rca_proposed_due_date { get; set; }
        public Nullable<int> rca_rootcause_id { get; set; }
        public Nullable<System.DateTime> rca_completed_date { get; set; }
    
        public virtual @case @case { get; set; }
    }
}
