//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucl_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ucl_data()
        {
            this.contacts = new HashSet<contact>();
            this.ealert_user_case_type = new HashSet<ealert_user_case_type>();
        }
    
        public int ucd_key { get; set; }
        public string ucd_title { get; set; }
        public string ucd_description { get; set; }
        public bool ucd_is_default { get; set; }
        public bool ucd_is_locked { get; set; }
        public int ucd_sort_order { get; set; }
        public string ucd_unique_id { get; set; }
        public Nullable<int> ucd_ucl_key { get; set; }
        public bool ucd_is_deleted { get; set; }
        public bool ucd_is_active { get; set; }
        public Nullable<System.DateTime> ucd_created_date { get; set; }
        public string ucd_created_by { get; set; }
        public Nullable<System.DateTime> ucd_modified_date { get; set; }
        public string ucd_modified_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ealert_user_case_type> ealert_user_case_type { get; set; }
        public virtual ucl ucl { get; set; }
    }
}
