//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login_verify
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsTwoFactRememberChecked { get; set; }
        public Nullable<System.DateTime> TwoFactVerifyExpiryDate { get; set; }
        public string MachineName { get; set; }
        public string MachineIpAddress { get; set; }
        public string BrowserKey { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
