//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_schedule_sleep
    {
        public long uss_key { get; set; }
        public string uss_user_id { get; set; }
        public System.DateTime uss_date { get; set; }
        public long uss_time_from { get; set; }
        public long uss_time_to { get; set; }
        public string uss_description { get; set; }
        public Nullable<bool> uss_is_active { get; set; }
        public string uss_created_by { get; set; }
        public string uss_created_by_name { get; set; }
        public System.DateTime uss_created_date { get; set; }
        public string uss_modified_by { get; set; }
        public string uss_modified_by_name { get; set; }
        public Nullable<System.DateTime> uss_modified_date { get; set; }
        public Nullable<System.DateTime> uss_time_from_calc { get; set; }
        public Nullable<System.DateTime> uss_time_to_calc { get; set; }
        public Nullable<decimal> uss_custome_rate { get; set; }
        public Nullable<int> uss_shift_key { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
