//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_user_schedule
    {
        public long uss_key { get; set; }
        public string uss_user_id { get; set; }
        public bool IsStrokeAlert { get; set; }
        public Nullable<long> DayNumber { get; set; }
        public Nullable<long> TIMEFROM { get; set; }
        public Nullable<long> TIMETO { get; set; }
    }
}
