//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_facility_physician
    {
        public int fap_key { get; set; }
        public System.Guid fap_fac_key { get; set; }
        public string fap_user_key { get; set; }
        public bool fap_is_active { get; set; }
        public string fac_name { get; set; }
        public bool fac_is_active { get; set; }
        public bool fap_is_on_boarded { get; set; }
        public bool fac_go_live { get; set; }
    }
}
