//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSpecialists.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class web2campaign_log
    {
        public int wcl_key { get; set; }
        public string wcl_error_code { get; set; }
        public string wcl_error_description { get; set; }
        public string wcl_raw_result { get; set; }
        public string wcl_user_agent { get; set; }
        public string wcl_browser_name { get; set; }
        public string wcl_created_by { get; set; }
        public string wcl_created_by_name { get; set; }
        public System.DateTime wcl_created_date { get; set; }
        public Nullable<int> wcl_cas_key { get; set; }
        public string wcl_request_url { get; set; }
        public Nullable<System.DateTime> wcl_request_send_time { get; set; }
        public Nullable<System.DateTime> wcl_response_received_time { get; set; }
        public Nullable<System.DateTime> wcl_reprocessed_date { get; set; }
        public Nullable<System.DateTime> wcl_error_mail_date { get; set; }
        public Nullable<System.DateTime> wcl_re_processed_date { get; set; }
        public Nullable<int> wcl_request_retry_count { get; set; }
    }
}
